server:
  port: 3344
spring:
  application:
    name: cloud-config-center  #注册进Eureka 服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liuya1993/springcloud-config-demo.git  #GitHub远程仓库地址
          # 搜索目录

          search-paths:
            - springcloud-config-demo
      #读取分支
      label: master

  rabbitmq:
    host: 192.168.159.129
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    bus-refresh:
      enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka