server:
  port: 80
spring:
  application:
    name: cloud-provider-hystrix-order
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
ribbon:
  ConnectionTimeout: 5000
  ReadTimeout: 5000

feign:
  hystrix:
    enabled: true